In [1]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("iris.csv")

In [7]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Data Quality Checks

In [13]:
df.isnull().sum()

sepal_length     8
sepal_width     16
petal_length     2
petal_width      2
species          3
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(2)

### Dataset Overview

In [9]:
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  142 non-null    float64
 1   sepal_width   134 non-null    float64
 2   petal_length  148 non-null    float64
 3   petal_width   148 non-null    float64
 4   species       147 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

In [11]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    142.000000   134.000000    148.000000   148.000000
mean       5.887324     2.990299      3.791216     1.212162
std        0.826413     0.386787      1.753478     0.759332
min        4.300000     2.000000      1.000000     0.100000
25%        5.200000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.200000      5.100000     1.800000
max        7.900000     4.100000      6.900000     2.500000

### Species Distribution

In [15]:
df["species"].value_counts()

species
Iris-versicolor    50
Iris-virginica     50
Iris-setosa        47
Name: count, dtype: int64

### NumPy Statistics

In [20]:
print("Mean Sepal Length:",
      np.mean(df["sepal_length"]))

Mean Sepal Length: 5.887323943661972

In [21]:
print("Median Petal Length:",
      np.median(df["petal_length"]))

Median Petal Length: nan

In [18]:
print("Standard Deviation:",
      np.std(df["sepal_length"]))

Standard Deviation: 0.8234981340298502

In [19]:
print("Variance:",
      np.var(df["sepal_length"]))

Variance: 0.678149176750645

### Correlation Analysis

In [22]:
print(df.corr(numeric_only=True))

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000     0.034714      0.864991     0.807364
sepal_width       0.034714     1.000000     -0.296486    -0.223054
petal_length      0.864991    -0.296486      1.000000     0.961220
petal_width       0.807364    -0.223054      0.961220     1.000000

### Feature Engineering (Creating my own column)

In [23]:
df["sepal_area"] = (
    df["sepal_length"] *
    df["sepal_width"]
)
print(df[["species","sepal_area"]].head())

       species  sepal_area
0  Iris-setosa       17.85
1  Iris-setosa       14.70
2  Iris-setosa       15.04
3  Iris-setosa       14.26
4  Iris-setosa       18.00

### Group by Analysis

In [24]:
species_summary = df.groupby("species").mean(numeric_only=True)

print(species_summary)

                 sepal_length  sepal_width  petal_length  petal_width  \
species
Iris-setosa             4.980     3.338235      1.462222     0.244444
Iris-versicolor         5.936     2.770000      4.260000     1.326000
Iris-virginica          6.588     2.974000      5.552000     2.026000

                 sepal_area
species
Iris-setosa       16.484444
Iris-versicolor   16.526200
Iris-virginica    19.684600

### Aggregate Functions

In [25]:
df.groupby("species").agg(
    {
        "sepal_length":["mean","min","max"],
        "petal_length":["mean","min","max"],
        "petal_width":["mean","min","max"]
    }
)

                sepal_length           petal_length           petal_width  \
                        mean  min  max         mean  min  max        mean
species
Iris-setosa            4.980  4.3  5.8     1.462222  1.0  1.9    0.244444
Iris-versicolor        5.936  4.9  7.0     4.260000  3.0  5.1    1.326000
Iris-virginica         6.588  4.9  7.9     5.552000  4.5  6.9    2.026000


                 min  max
species
Iris-setosa      0.1  0.6
Iris-versicolor  1.0  1.8
Iris-virginica   1.4  2.5

### Sorting

In [26]:
largest_flowers=df.sort_values(
    by="petal_length",
    ascending=False
)

In [27]:
largest_flowers.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
118,7.7,2.6,6.9,2.3,Iris-virginica,20.02
122,7.7,2.8,6.7,2.0,Iris-virginica,21.56
117,7.7,3.8,6.7,2.2,Iris-virginica,29.26
105,7.6,3.0,6.6,2.1,Iris-virginica,22.80
131,7.9,3.8,6.4,2.0,Iris-virginica,30.02

### Filtering

In [28]:
large_petals = df[
    df["petal_length"] > 5
]

In [29]:
large_petals.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
83,6.0,2.7,5.1,1.6,Iris-versicolor,16.20
100,6.3,3.3,6.0,2.5,Iris-virginica,20.79
101,5.8,2.7,5.1,1.9,Iris-virginica,15.66
102,7.1,3.0,5.9,2.1,Iris-virginica,21.30
103,6.3,2.9,5.6,1.8,Iris-virginica,18.27

In [30]:
species_summary.to_csv(
    "species_summary.csv"
)